[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyseto"
version = "1.7.3"
description = "A Python implementation of PASETO/PASERK."
authors = ["Ajitomi Daisuke <dajiaji@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dajiaji/pyseto"

include = [
  "CHANGES.rst",
  "docs",
  "poetry.lock",
  "tests",
  "tox.ini",
]

exclude = [
  "docs/_build",
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
cryptography = "41.0.3"
pycryptodomex = "^3.18.0"
passlib = {extras = ["argon2"], version = "^1.7.4"}
iso8601 = ">=1.0.2,<3.0.0"
Sphinx = {version = ">=4.3.2,<7.0.0", optional = true, extras = ["docs"]}
sphinx-rtd-theme = {version = "^1.2.1", optional = true, extras = ["docs"]}


[tool.poetry.extras]
docs = [
  "Sphinx",
  "sphinx-rtd-theme",
  "sphinx-autodoc-typehints",
]

[tool.poetry.dev-dependencies]
pytest = "^7.4"
pytest-cov = "^4.1.0"
tox = "^4.8.0"
pre-commit = "^3.3.3"
freezegun = "^1.2.2"
